voxpupuli/puppet-iis

- manifests/manage_virtual_directory.pp
Define to manage virtual directories. E.g:
```powershell
iis::manage_virtual_directory { ${virtual_directory_name} :
site_name => 'Default Web Site',
directory => ${virtual_directory_name},
path      => ${virtual_directory_path}
}
```
> Manage virtual directory

- manifests/manage_virtual_directory.pp
- Adds missing quotes around ${path} variable in powershell
logic which could cause issues
> Issue-64 - Missing quotes around path for virtual_directory

- manifests/manage_app_pool.pp
Expanding the accepted range of .Net installations to include .Net 4.5
> allow for .Net 4.5

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool - add periodic recycle control
new param left default undef
logic in class handles undef
caller set to 0 to disable periodic app pool recycling
minutes value converted to ticks and given to powershell for timespan
constructor as int64 max value is powerhsell $([int64]::MaxValue)
validation will reject negatives or out of max bound
> manage_app_pool - add periodic recycle control

- manifests/manage_app_pool.pp
Fixes issue #86 - app require parameter to require the exec creating the application pool.
> Fix issue #86

- .puppet-lint.rc
- .rubocop.yml
- .sync.yml
- .travis.yml
- CONTRIBUTING.md
- Gemfile
- Rakefile
- lib/facter/iis_version.rb
- spec/classes/coverage_spec.rb
- spec/defines/manage_app_pool_spec.rb
- spec/defines/manage_binding_spec.rb
- spec/defines/manage_site_spec.rb
- spec/defines/manage_site_state_spec.rb
- spec/defines/manage_virtual_application_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- Perform modulesync with tagged version 0.3.0 of modulesync_config
- Remove puppet-lint-rc
- Exclude non-Windows nodesets from being managed by modulesync
> Perform modulesync (0.3.0)

- .sync.yml
- Gemfile
- spec/acceptance/iis_install_spec.rb
- spec/acceptance/iis_site_spec.rb
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/windows-2012-serverstandard-x64.yml
- spec/acceptance/nodesets/windows-2012R2-serverstandard-x64.yml
- spec/spec_helper_acceptance.rb
* Adds new tests for iis class that installs IIS with Windows features
* Adds standard Windows boilerplate
> Updates acceptance testing

- manifests/manage_app_pool.pp
as i am in the need to have this solved, here is a checkout you can incorporate
resolution for https://github.com/voxpupuli/puppet-iis/issues/104
thanks
d
> enclose user and pwd between ""

- spec/defines/manage_app_pool_spec.rb
After #104, I realised we had no test coverage for `manage_app_pool`
Just basics for now, would be good to add a spec for `apppool_username` which was causing the issue in #104
> Adds spec for manage_app_pool

- lib/puppet/provider/iis_site/powershell.rb
- lib/puppet/type/iis_site.rb
- spec/defines/manage_binding_spec.rb
Fixes current errors in Travis
> Fix rubocop failures

- manifests/manage_app_pool.pp
- spec/defines/manage_app_pool_spec.rb
Rebase of #118
* Squashes commits into one modular commit
* Adds rspec to cover new parameter
> Add idle action timeout

- manifests/manage_binding.pp
- spec/defines/manage_binding_spec.rb
SslFlags is not a valid argument for Remove-WebBinding (https://technet.microsoft.com/en-us/library/hh867895(v=wps.630).aspx). Removing.
> Remove -SslFlags from Remove-WebBinding argument list

- .sync.yml
- Gemfile
* No longer need to use fork! Work has been pushed upstream properly
* Update sync file with changes
> Pin to working Windows beaker and beaker-rspec

- manifests/manage_app_pool.pp
- spec/defines/manage_app_pool_spec.rb
Rebase of https://github.com/voxpupuli/puppet-iis/pull/125 with tests
> Correcting idle timeout

- .sync.yml
Commenting it out in .sync.yml and adding note about issue that caused it.
> Get rid of spec_helper_acceptance for real this time

- .msync.yml
- Gemfile
- Rakefile
- lib/puppet/provider/iis_site/powershell.rb
- spec/default_facts.yml
- spec/spec_helper.rb
- spec/unit/puppet/type/iis_application_spec.rb
- spec/unit/puppet/type/iis_pool_spec.rb
> modulesync 0.11.1

- .gitignore
- .msync.yml
- .rubocop.yml
- Gemfile
- spec/acceptance/iis_install_spec.rb
- spec/acceptance/iis_site_spec.rb
- spec/defines/manage_app_pool_spec.rb
- spec/defines/manage_binding_spec.rb
- spec/spec_helper.rb
> modulesync 0.15.0

- spec/defines/manage_binding_spec.rb
- templates/inspect-certificate-binding.ps1.erb
> Changed if statement to be an -Or command.

- .msync.yml
- .rubocop.yml
- .travis.yml
- spec/spec_helper.rb
> modulesync 0.16.11

- manifests/manage_app_pool.pp
https://github.com/voxpupuli/puppet-iis/issues/179
Fixes issue 179 where a system assembly was not loaded for 4 different actions within manage_app_pool. 
Testing was done on Windows Server 2012R2 and Powershell 5.0
> Fix issue 179

- .github/CONTRIBUTING.md
- .gitignore
- .msync.yml
- .overcommit.yml
- .rspec_parallel
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- lib/puppet/provider/iis_pool/powershell.rb
- lib/puppet/provider/iis_site/powershell.rb
- spec/acceptance/nodesets/archlinux-2-x64.yml
- spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml
- spec/acceptance/nodesets/ec2/image_templates.yaml
- spec/acceptance/nodesets/ec2/rhel-73-x64.yml
- spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml
- spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml
- spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml
- spec/unit/facter/util/fact_iis_version_spec.rb
- spec/unit/puppet/type/iis_pool_spec.rb
> modulesync 0.21.3
