- lib/facter/iis_version.rb
Hi,
Both me an my puppet master guy was not totally read up on the puppet-iis module so not knowing there was a fact included in the module for checking the version of IIS I kind of made my own, which of course led in to a minor war with your fact when pluginsync changes iis_version.rb back and forth.
Anyway I used ruby to check my iis version, which I think might be an good alternative to your wrapped powershell command, especially as your script returns a value (empty string) when there is no iis installed, where as mine returns nothing so the fact will only be present on systems having iis installed. I think that is a pretty way of doing it and thought I'd share it with you. Hopefully you like it aotherwise just discard it ;-).
> Alternate way of getting the iis_version fact

- manifests/manage_app_pool.pp
Added start_mode and rapid_fail_protection.  I also reorganized the parameters to be on separate lines as mentioned in issue 63 to make it a little easier to read.  Let me know if I should separate this out into a different commit.
> Adding start_mode and rapid_fail_protection app pool advanced settings

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
new params kept optional as undef to allow for backwards compatibility,
logic in class will handle undef
Caller MUST specify $apppoolusername $apppoolpassword if using
"SpecificUser" identity type
> manage_app_pool - added app pool identity capability

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool added ability to set idle timeout
new params set default undef for backward compatibility
logic in class handles this
Caller set to 0 will disable this feature in IIS for given app pool
>  manage_app_pool added ability to set idle timeout

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool - add max processes control
new params kept undef defaults for backward compatibility
setting 0 here will let IIS detect optimal max processes count on NUMA
aware system.
not enforcing a max on maximum processes you can throw at an app pool,
admin knows system.  it's a (signed) int64
>  manage_app_pool - add max processes control

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool - add app pool max queue length control
new param kept default undef for backward compatibility
app pool max queue length must be set 10 <= n <= 65535
validation will fail a catalog if outside these bounds
> manage_app_pool - add app pool max queue length control

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool - add scheduled recycling control
new param left undef default for backward compatibility
logic in class handles undef
caller provide array of time strings ['hh:mm:ss','...'] - empty array to
clear scheduled recycling on an app pool
> manage_app_pool - add scheduled recycling control

- README.md
- manifests/manage_app_pool.pp
- metadata.json
- spec/defines/manage_app_pool_spec.rb
manage_app_pool - add recycle logging control
new param default undef for backward compatibility
logic in class handles undef
caller specify one or more values from
['Time','Requests','Schedule','IsapiUnhealthy','OnDemand','ConfigChange','PrivateMemory']
empty array [] will clear current logging on app pool (set to no logging)
> manage_app_pool - add recycle logging control

- manifests/manage_binding.pp
- spec/defines/manage_binding_spec.rb
- templates/create-certificate-binding.ps1.erb
- templates/inspect-certificate-binding.ps1.erb
Added two attributes to manage_binding defined type:
store
sslFlag
New-WebBinding now uses SslFlags parameter.
Templates updated to search for ssl bindings with host headers.
Example Usage:
iis::manage_binding { "${site_name}-443":
site_name              => $site_name,
protocol               => 'https',
port                   => '443',
host_header            => $site_name,
certificate_thumbprint => $cert_thumbprint,
store                  => 'WebHosting',
sslFlag                => '1',
require                => Sslcertificate[ "${site_name}" ],
}
> Add support for SNI

- manifests/manage_virtual_application.pp
The name "foo/bar" is a valid name, but when you search for it, it was renamed to "foo\\bar". So, it is necessary to replace it to perform the search.
> Fixing virtual application names

- README.md
- manifests/features/application_deployment.pp
- manifests/features/common_http.pp
- manifests/features/health_and_diagnostics.pp
- manifests/features/management_tools.pp
- manifests/features/performance.pp
- manifests/features/security.pp
- manifests/manage_site.pp
- spec/defines/manage_site_spec.rb
Had to recreate my repo due to irrecoverable conflicts.
Our organization uses the site ID of each web service for logging sanity and have a need to have this set. I added the variable and the logic to add one if not supplied and verify it isn't in use.
Also, during my usage, while attempting to use the installation mechanic, I found the versions listed in the .pp files were reversed. IIS-* is used in WS2008/R2 and Web-* in WS2012/R2, not the other way around. Tested locally and works in our infrastructure.
> Added site_id and related logic, testing, and documentation.

- Gemfile
- lib/facter/iis_version.rb
- lib/facter/util/registryiis.rb
- spec/unit/facter/iis_version_spec.rb
* Simplifying registry logic (don't need block, can just access directly)
* `(version[8..-1] is not super intiutive
* Changing to gsub to make more readable `gsub(/Version\s+/,'')`
* Moving registry logic to util class to make mocking easier
* Adding spec, mocking the logic from the util class
> Adding spec for `iis_version` fact

- manifests/manage_binding.pp
* The present value for the ensure attribute is ambiguous. You should use file instead.
> Changes to use 'file' over 'present'

- lib/facter/iis_version.rb
In our combined Windows/Linux environment, running puppet 3.8.7, we got this error:
Error loading fact /var/lib/puppet/lib/facter/iis_version.rb: /var/lib/puppet/lib/facter/iis_version.rb:2: syntax error, unexpected ':', expecting kEND
confine kernel: :windows
Using the 'former' syntax makes the fact work again.
> Make the fact work on RHEL6 systems

- spec/unit/puppet/type/iis_application_spec.rb
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<Puppet::ResourceError: Parameter path failed on Iis_application[test_application]: Validate method failed for class path: File paths must be fully qualified, not '//remote/Temp'>. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/petersouter/projects/voxpupuli-iis/spec/unit/puppet/type/iis_applicati …
```
> Updates spec to silence warning

- .sync.yml
.sync.yml was managing gemfile and squashing gems we needed to run spec tests.
> Unmanage Gemfile in .sync.yml

- LICENSE
- metadata.json
Relicensing can only be done with the permission of all the copyright
holders.
> Revert metadata.json license back to MIT

- manifests/features/application_deployment.pp
- manifests/features/common_http.pp
- manifests/features/health_and_diagnostics.pp
- manifests/features/management_tools.pp
- manifests/features/performance.pp
- manifests/features/security.pp
Windows 10.0 supports all of the following WindowsFeatures:
- Web-Static-Content
- Web-Http-Errors
- Web-Default-Doc
- Web-Http-Logging
- Web-Request-Monitor
- Web-Mgmt-Tools
- Web-Mgmt-Console
- Web-Stat-Compression
- Web-Dyn-Compression
- Web-Filtering
> Adding support for Windows 10.0 in `manifests/features`

- CHANGELOG.md
- metadata.json
The big thing in this version is a refactor of IIS sites and ending support for server 2008. 
Per @igalic's suggestion, we should wait for input from @WhatsARanjit for confirmation before releasing.
> Prepare for version 3.0.0

- CHANGELOG.md
- README.md
- manifests/init.pp
- metadata.json
http://forge.puppet.com/puppetlabs/iis/4.0.0 is live and ships in the 5.0.0 of the windows pack: https://forge.puppet.com/puppetlabs/windows/5.0.0
The previously released version is 3.0.0, though the metadata was bumped to 4.0.0-rc0.
We can either do a 3.1.0 or a 99.99.99 as per https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli
> Release 3.1.0 for deprecation

- README.md
A link text and link URL should not be separated by whitespace - that breaks rendering. Instead, they should be together and then GitHub will properly present the link as a link instead of splitting it up.
> Remove bad spaces from README links
